const provinces = [
    'Hồ Chí Minh',
    'Hà Nội',
    'Đà Nẵng',
    'An Giang',
    'Bà Rịa - Vũng Tàu',
    'Bình Dương',
    'Bình Phước',
    'Bình Thuận',
    'Bình Định',
    'Bạc Liêu',
    'Bắc Giang',
    'Bắc Kạn',
    'Bắc Ninh',
    'Bến Tre',
    'Cao Bằng',
    'Cà Mau',
    'Cần Thơ',
    'Gia Lai',
    'Hà Giang',
    'Hà Nam',
    'Hà Tĩnh',
    'Hòa Bình',
    'Hưng Yên',
    'Hải Dương',
    'Hải Phòng',
    'Hậu Giang',
    'Khánh Hòa',
    'Kiên Giang',
    'Kon Tum',
    'Lai Châu',
    'Long An',
    'Lào Cai',
    'Lâm Đồng',
    'Lạng Sơn',
    'Nam Định',
    'Nghệ An',
    'Ninh Bình',
    'Ninh Thuận',
    'Phú Thọ',
    'Phú Yên',
    'Quảng Bình',
    'Quảng Nam',
    'Quảng Ngãi',
    'Quảng Ninh',
    'Quảng Trị',
    'Sóc Trăng',
    'Sóc Sơn',
    'Sơn La',
    'Thanh Hóa',
    'Thái Bình',
    'Thái Nguyên',
    'Thừa Thiên Huế',
    'Tiền Giang',
    'Trà Vinh',
    'Tuyên Quang',
    'Tây Ninh',
    'Vĩnh Long',
    'Vĩnh Phúc',
    'Yên Bái',
    'Điện Biên',
    'Đắk Lắk',
    'Đắk Nông',
    'Đồng Nai',
    'Đồng Tháp',
];

const colors = [
    'SÁNG',
    'ĐẬM',
    'TRUNG',
    'XÁM',
    'NÂU',
    'NAVY',
    'VÀNG',
    'XANH',
    'KEM',
    'CAM',
    'CAM ĐẤT',
    'HỒNG',
    'HỒNG ĐẬM',
    'ĐEN',
    'ĐEN CHÌ',
    'ĐEN SẪM',
    'ĐEN NHẠT',
    'ĐEN KHÓI',
    'ĐEN ML',
    'XANH NAVY',
    'XANH LÁ',
    'XANH DƯƠNG',
    'XANH MINT',
    'XANH BIỂN',
    'XANH XÁM',
    'XANH NGỌC',
    'XANH LAM',
    'XANH RÊU',
    'XANH LƠ',
    'XANH BÍCH',
    'XANH CỔ VỊT',
    'XANH NHẠT',
    'XANH ĐẬM',
    'XANH TRUNG',
    'XANH SÁNG',
    'TRẮNG',
    'TRẮNG PHỐI NAVY',
    'TRẮNG NÂU',
    'TÍM',
    'TÍM THAN',
    'ĐỎ',
    'ĐỎ ĐÔ',
    'KẺ ĐEN',
    'KẺ XANH',
    'KẺ HỒNG',
];

const sizes = ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'];
const prices = [
    {
        minValue: 0,
        maxValue:100000
    },
    {
        minValue: 100000,
        maxValue:200000
    },
    {
        minValue: 200000,
        maxValue:350000
    },
    {
        minValue: 350000,
        maxValue:500000
    },
    {
        minValue: 500000,
        maxValue:700000
    },
    {
        minValue: 700000,
        maxValue:100000000
    },
]

module.exports = {provinces, colors,sizes,prices};
